name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  secret-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: print git config
        run: git config --local --list
      - name: secret action
        run: echo "${{secrets.SUPER_SECRET_TOKEN}}" > /dev/null
      
