name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  secret-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: secret action
        run: echo "SUPER_SECRET_TOKEN" > /dev/null
      
